### ISSUE TITLE
Advantage over flask-sqlalchemy

### ISSUE THREAD

**Issue by hamidfzm** [rshk/flask-sqlalchemy-core#1]
Have you seen https://github.com/mitsuhiko/flask-sqlalchemy? What is your project advantages over  @mitsuhiko's flask-sqlalchemy?

**Comment by rshk** [comment]
yep, 'course I have. Main difference with this one is I'm supporting SQLAlchemy [Core](https://docs.sqlalchemy.org/en/latest/core/), while flask-sqlalchemy is for using the [ORM](https://docs.sqlalchemy.org/en/latest/orm/). Then, I'm providing a "cleaner" integration, with fewer of the "magic", and with a few extras that greatly help with testing (eg. django-style wrapping test cases in a transaction, to speed things up).
